### ISSUE TITLE
unwrap of None 

### ISSUE THREAD

**Issue by matthiaskrgr** [langston-barrett/tree-splicer#11]
Hi, I just [upgraded](https://github.com/matthiaskrgr/icemaker/commit/ad2b9d58351d7f3bfe595ff4362768252ccbcbf3) and it looks like I'm hitting a None sometimes:

````
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-splicer-0.3.0/src/splice.rs:170:50
stack backtrace:
   0:     0x557a8bbee5da - std::backtrace_rs::backtrace::libunwind::trace::h3973f51617998fc6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557a8bbee5da - std::backtrace_rs::backtrace::trace_unsynchronized::hc880f45678a36b06
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557a8bbee5da - std::sys_common::backtrace::_print_fmt::h0c5a990bb8ef31fa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557a8bbee5da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h55a8e98b4c6161da
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557a8bc14bfe - core::fmt::write::h4c40d77c4903afa0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/fmt/mod.rs:1254:17
   5:     0x557a8bbe9e75 - std::io::Write::write_fmt::ha3b362d3dcfb999f
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/io/mod.rs:1698:15
   6:     0x557a8bbee3a5 - std::sys_common::backtrace::_print::h8269abb9d4b9ac2e
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557a8bbee3a5 - std::sys_common::backtrace::print::h475ddad52d027480
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557a8bbefddf - std::panicking::default_hook::{{closure}}::hdb1a9b91764be170
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:271:22
   9:     0x557a8bbefb1b - std::panicking::default_hook::hb3624b5fb0dd82aa
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:290:9
  10:     0x557a8bbf03e8 - std::panicking::rust_panic_with_hook::h34c77a71befec972
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:692:13
  11:     0x557a8bbf02a2 - std::panicking::begin_panic_handler::{{closure}}::hb5ae8193b4163d8b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:581:13
  12:     0x557a8bbeea46 - std::sys_common::backtrace::__rust_end_short_backtrace::h53bbfcb82ab0fc3b
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x557a8bbefff2 - rust_begin_unwind
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:579:5
  14:     0x557a8bc13093 - core::panicking::panic_fmt::h712e519910af2aa1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:64:14
  15:     0x557a8bc1312d - core::panicking::panic::h7c5f6c047dc85cd8
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panicking.rs:114:5
  16:     0x557a8b8b17e0 - core::option::Option<T>::unwrap::h9cb6e9fc48740dd2
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:952:21
  17:     0x557a8b8d1522 - tree_splicer::splice::Splicer::splice_node::h4e9c6fd8f475db72
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-splicer-0.3.0/src/splice.rs:170:17
  18:     0x557a8b8d1c7b - tree_splicer::splice::Splicer::splice_tree::h0cc0bdf127f11bc6
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-splicer-0.3.0/src/splice.rs:197:17
  19:     0x557a8b8d2239 - <tree_splicer::splice::Splicer as core::iter::traits::iterator::Iterator>::next::hd4cb1e3aeb6c99bc
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tree-splicer-0.3.0/src/splice.rs:227:9
  20:     0x557a8b6a2db2 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::ha343e3fdcbbb4976
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/iter/adapters/map.rs:103:9
  21:     0x557a8b6579d8 - alloc::vec::Vec<T,A>::extend_desugared::h23b86eb7448b9eba
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/vec/mod.rs:2815:35
  22:     0x557a8b66336a - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::ha5a4d44e95721fb2
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/vec/spec_extend.rs:17:9
  23:     0x557a8b6467f6 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h79cd4aaf0566e8b6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  24:     0x557a8b663f1d - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h56cf5a32f43dc6e6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/vec/spec_from_iter.rs:33:9
  25:     0x557a8b662068 - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::ha2975bc5118949f4
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/vec/mod.rs:2715:9
  26:     0x557a8b6a5b3d - core::iter::traits::iterator::Iterator::collect::h9807e3792bdbf160
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/iter/traits/iterator.rs:1896:9
  27:     0x557a8b63e3e8 - icemaker::fuzz_tree_splicer::splice_file::hcf984e9ffc5e3e57
                               at /home/matthias/vcs/github/icemaker/src/fuzz_tree_splicer.rs:41:5
  28:     0x557a8b729218 - icemaker::codegen_tree_splicer::{{closure}}::h026d66a949cadddf
                               at /home/matthias/vcs/github/icemaker/src/main.rs:2029:13
  29:     0x557a8b71ddc2 - core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut::h116ddece1527887d
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/ops/function.rs:274:13
  30:     0x557a8b71e0ff - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h1f1d55357a0611a2
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/ops/function.rs:310:13
  31:     0x557a8b70f2e1 - core::option::Option<T>::map::h8b05576e975d7b54
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/option.rs:1101:29
  32:     0x557a8b6a2f6b - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::hb439ae4dab217733
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/iter/adapters/map.rs:103:9
  33:     0x557a8b56c090 - rayon::iter::plumbing::Folder::consume_iter::ha49d082ed4e2b8f7
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:178:21
  34:     0x557a8b6d028a - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::hb92ba8cea0270f03
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/map.rs:248:21
  35:     0x557a8b594bf5 - rayon::iter::plumbing::Producer::fold_with::hb17384f1915af082
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:110:9
  36:     0x557a8b6082b9 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd1bfc40a5dc693aa
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:438:13
  37:     0x557a8b60c662 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::hd5344c492e9438f9
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  38:     0x557a8b6238ec - rayon_core::join::join_context::call_a::{{closure}}::h50f11c3c4745d62d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  39:     0x557a8b6e2220 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc2c8bd3bec1065ef
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panic/unwind_safe.rs:271:9
  40:     0x557a8b573d85 - std::panicking::try::do_call::h3e950bc0b724bcc0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:487:40
  41:     0x557a8b5790bb - __rust_try
  42:     0x557a8b5723a2 - std::panicking::try::hdd31d71c6a96e2a1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:451:19
  43:     0x557a8b57b8e6 - std::panic::catch_unwind::h01817161d2564fcb
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panic.rs:140:14
  44:     0x557a8b63f533 - rayon_core::unwind::halt_unwinding::h6de2f4292e117723
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  45:     0x557a8b61f647 - rayon_core::join::join_context::{{closure}}::he61397b982448c7d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  46:     0x557a8b683832 - rayon_core::registry::in_worker::h9105430fe65c3507
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  47:     0x557a8b617b1a - rayon_core::join::join_context::h24aa7ea6c9c886c4
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  48:     0x557a8b608160 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd1bfc40a5dc693aa
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  49:     0x557a8b60c662 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::hd5344c492e9438f9
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  50:     0x557a8b6238ec - rayon_core::join::join_context::call_a::{{closure}}::h50f11c3c4745d62d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  51:     0x557a8b6e2220 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc2c8bd3bec1065ef
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panic/unwind_safe.rs:271:9
  52:     0x557a8b573d85 - std::panicking::try::do_call::h3e950bc0b724bcc0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:487:40
  53:     0x557a8b5790bb - __rust_try
  54:     0x557a8b5723a2 - std::panicking::try::hdd31d71c6a96e2a1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:451:19
  55:     0x557a8b57b8e6 - std::panic::catch_unwind::h01817161d2564fcb
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panic.rs:140:14
  56:     0x557a8b63f533 - rayon_core::unwind::halt_unwinding::h6de2f4292e117723
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  57:     0x557a8b61f647 - rayon_core::join::join_context::{{closure}}::he61397b982448c7d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  58:     0x557a8b683832 - rayon_core::registry::in_worker::h9105430fe65c3507
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:984:13
  59:     0x557a8b617b1a - rayon_core::join::join_context::h24aa7ea6c9c886c4
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:132:5
  60:     0x557a8b608160 - rayon::iter::plumbing::bridge_producer_consumer::helper::hd1bfc40a5dc693aa
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:416:47
  61:     0x557a8b60c662 - rayon::iter::plumbing::bridge_producer_consumer::helper::{{closure}}::hd5344c492e9438f9
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-1.7.0/src/iter/plumbing/mod.rs:418:21
  62:     0x557a8b6238ec - rayon_core::join::join_context::call_a::{{closure}}::h50f11c3c4745d62d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:124:17
  63:     0x557a8b6e2220 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc2c8bd3bec1065ef
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panic/unwind_safe.rs:271:9
  64:     0x557a8b573d85 - std::panicking::try::do_call::h3e950bc0b724bcc0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:487:40
  65:     0x557a8b5790bb - __rust_try
  66:     0x557a8b5723a2 - std::panicking::try::hdd31d71c6a96e2a1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:451:19
  67:     0x557a8b57b8e6 - std::panic::catch_unwind::h01817161d2564fcb
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panic.rs:140:14
  68:     0x557a8b63f533 - rayon_core::unwind::halt_unwinding::h6de2f4292e117723
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  69:     0x557a8b61f647 - rayon_core::join::join_context::{{closure}}::he61397b982448c7d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/join/mod.rs:142:24
  70:     0x557a8b676c62 - rayon_core::registry::Registry::in_worker_cold::{{closure}}::{{closure}}::h65b4baf778c03c7d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:541:21
  71:     0x557a8b689a21 - rayon_core::job::JobResult<T>::call::{{closure}}::h0d42b297e3f601c4
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:41
  72:     0x557a8b6e1670 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h388d57225f3552df
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panic/unwind_safe.rs:271:9
  73:     0x557a8b573761 - std::panicking::try::do_call::h2218fd6db97a4960
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:487:40
  74:     0x557a8b5790bb - __rust_try
  75:     0x557a8b56efc2 - std::panicking::try::h6697bef99f857bbf
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:451:19
  76:     0x557a8b57c3d6 - std::panic::catch_unwind::hec8a9da4b19f0c57
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panic.rs:140:14
  77:     0x557a8b6403c7 - rayon_core::unwind::halt_unwinding::hff1087b432ef692d
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/unwind.rs:17:5
  78:     0x557a8b686a99 - rayon_core::job::JobResult<T>::call::h274ffa3eab6db20f
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:218:15
  79:     0x557a8b698f84 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7a7376f17c1fcc7c
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:120:32
  80:     0x557a8b81eff0 - rayon_core::job::JobRef::execute::h805c2d4e30b97193
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/job.rs:64:9
  81:     0x557a8b831080 - rayon_core::registry::WorkerThread::execute::hab7226ab1d30f8e1
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:874:9
  82:     0x557a8b830de9 - rayon_core::registry::WorkerThread::wait_until_cold::hc3b9554880e18a53
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:820:17
  83:     0x557a8b830bd2 - rayon_core::registry::WorkerThread::wait_until::h58bce0f1d33c6a84
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:803:13
  84:     0x557a8b831641 - rayon_core::registry::main_loop::h78be0e65456a45ad
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:948:5
  85:     0x557a8b82c896 - rayon_core::registry::ThreadBuilder::run::h3f656c057cfc8c00
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:54:18
  86:     0x557a8b82ccfd - <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}}::h2e22ba63d1f4048f
                               at /home/matthias/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rayon-core-1.11.0/src/registry.rs:99:20
  87:     0x557a8b8455d9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbb6074fe7e703186
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys_common/backtrace.rs:134:18
  88:     0x557a8b81a6bd - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hc153e616e5970e41
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/thread/mod.rs:525:17
  89:     0x557a8b83f531 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0746b9e057a2aff7
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/panic/unwind_safe.rs:271:9
  90:     0x557a8b846c62 - std::panicking::try::do_call::haf9f3779d7d56aa1
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:487:40
  91:     0x557a8b8488bb - __rust_try
  92:     0x557a8b8469d2 - std::panicking::try::h9c71e0cebf6c2de6
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panicking.rs:451:19
  93:     0x557a8b815d4a - std::panic::catch_unwind::h9dc97c800101d3e5
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/panic.rs:140:14
  94:     0x557a8b81a435 - std::thread::Builder::spawn_unchecked_::{{closure}}::ha875271c990945e0
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/thread/mod.rs:524:30
  95:     0x557a8b80546f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h676e1e723da72acb
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/core/src/ops/function.rs:250:5
  96:     0x557a8bbf5e43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5465857e83d6d8ca
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  97:     0x557a8bbf5e43 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha9ee3b71411efa49
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/alloc/src/boxed.rs:1988:9
  98:     0x557a8bbf5e43 - std::sys::unix::thread::Thread::new::thread_start::hade30c6a6cbcfe88
                               at /rustc/1459b3128e288a85fcc4dd1fee7ada2cdcf28794/library/std/src/sys/unix/thread.rs:108:17
  99:     0x7fc55ef2ebb5 - <unknown>
 100:     0x7fc55efb0d90 - <unknown>
 101:                0x0 - <unknown>
````

**Comment by langston-barrett** [comment]
Sorry! That one is fixed on `main`: https://github.com/langston-barrett/tree-splicer/commit/75db6e64b0bf6ab8e44c08d08774fecccd9e5c2e

I'll do a new release.

**Comment by langston-barrett** [comment]
I pushed v0.3.1. Thanks for noticing this!
